### ISSUE TITLE
Log4j errors with beta 58

### ISSUE THREAD

**Issue by AlexIIL** [QuiltMC/quilt-loader#219]
Both in quilt-loader's development environment and in production (no mods) I get the following error messages:

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Reconfiguration failed: No configuration found for '5cb0d902' at 'null' in 'null'
```

In addition, in production I now get many errors like this:

```java
ERROR StatusLogger Unable to create Lookup for env
 java.lang.ClassCastException: class org.apache.logging.log4j.core.lookup.EnvironmentLookup
	at java.base/java.lang.Class.asSubclass(Class.java:3956)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:84)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:105)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:135)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:74)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:140)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:230)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at org.spongepowered.asm.service.modlauncher.LoggerAdapterLog4j2.<init>(LoggerAdapterLog4j2.java:47)
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncher.createLogger(MixinServiceModLauncher.java:194)
	at org.spongepowered.asm.service.MixinServiceAbstract.getLogger(MixinServiceAbstract.java:261)
	at org.spongepowered.asm.service.MixinServiceAbstract.<init>(MixinServiceAbstract.java:91)
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncher.<init>(MixinServiceModLauncher.java:119)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:238)
	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:204)
	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:198)
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:152)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by AlexIIL** [comment]
Fixed in https://github.com/QuiltMC/quilt-loader/commit/ac35da6d51a3701454306d86af1177f6ef8380d2
