### ISSUE TITLE
Java installer crashing due to json error

### ISSUE THREAD

**Issue by TheFruxz** [QuiltMC/quilt-loader#261]
Exception occuring after pressing the install button

```
Installing Minecraft client of version 1.19.3 with loader version 0.18.3
Creating profile launch json
Creating new profile
Failed to install client
java.util.concurrent.CompletionException: org.quiltmc.installer.lib.json5.exception.MalformedSyntaxException: Found potentially valid JSON5, but invalid JSON while in strict mode $.version
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: org.quiltmc.installer.lib.json5.exception.MalformedSyntaxException: Found potentially valid JSON5, but invalid JSON while in strict mode $.version
	at org.quiltmc.installer.lib.json5.JsonReader.syntaxError(JsonReader.java:1645)
	at org.quiltmc.installer.lib.json5.JsonReader.isJson5(JsonReader.java:1515)
	at org.quiltmc.installer.lib.json5.JsonReader.peekNumber(JsonReader.java:1154)
	at org.quiltmc.installer.lib.json5.JsonReader.doPeek(JsonReader.java:959)
	at org.quiltmc.installer.lib.json5.JsonReader.peek(JsonReader.java:405)
	at org.quiltmc.installer.Gsons.read(Gsons.java:41)
	at org.quiltmc.installer.Gsons.read(Gsons.java:61)
	at org.quiltmc.installer.LauncherProfiles.updateProfiles(LauncherProfiles.java:57)
	at org.quiltmc.installer.action.InstallClient.lambda$run$2(InstallClient.java:144)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 9 more
```

**Comment by TheFruxz** [comment]
Wrong repository
