### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by ioococ** [QuiltMC/quilt-loader#372]
Using quilt loader 0.21.0 and installing indium and lambdabettergrass, starting under MC 1.20 will cause blocks to fail to render. This problem will not occur using quilt loader 0.20.0

[mods and logs.zip](https://github.com/QuiltMC/quilt-loader/files/12811503/mods.and.logs.zip)

![批注 2023-10-05 095719](https://github.com/QuiltMC/quilt-loader/assets/51018049/2b0a83a6-e51c-4ee1-826d-6e62dcd52a68)

**Comment by AlexIIL** [comment]
I'm guessing this repeated stacktrace in the logs hints towards the problem, although I don't know how to fix it yet:
```
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:136)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$zzd000$indium$onRenderBlock(ChunkRenderRebuildTask.java:541)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:104)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:286)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:328)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:55)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:98)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:1075)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:52)
	at dev.lambdaurora.lambdabettergrass.model.LBGBakedModel.emitBlockQuads(LBGBakedModel.java:117)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	... 5 more
```

**Comment by ioococ** [comment]
> I'm guessing this repeated stacktrace in the logs hints towards the problem, although I don't know how to fix it yet:
> 
> ```
> net.minecraft.class_148: Tessellating block in world - Indium Renderer
> 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:136)
> 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$zzd000$indium$onRenderBlock(ChunkRenderRebuildTask.java:541)
> 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:104)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:286)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:328)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> Caused by: java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
> 	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:55)
> 	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:98)
> 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:1075)
> 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:52)
> 	at dev.lambdaurora.lambdabettergrass.model.LBGBakedModel.emitBlockQuads(LBGBakedModel.java:117)
> 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
> 	... 5 more
> ```

Yes, I also noticed this exception.

**Comment by ioococ** [comment]
Problem solved, I deleted Indium 😆
