### ISSUE TITLE
io.netty.handler.codec.DecoderException: Unknown serializer type 111

### ISSUE THREAD

**Issue by Conobi** [QuiltMC/quilt-loader#379]
Hey,
I've been trying to debug an issue that occurs really randomly, more with some mods (ModernFix, KubeJS, Carpet Mod, Debugify, Build Guide, but even without these mods it can rarely occurs), and than I'm totally unable to debug (the stack trace is obfuscated at this level).
It doesn't happen in singleplayer (nor in LAN mode AFAIK), only on server.

When playing on the server, after playing a while (it can be 5 min, 5 hours, or even days), me and other players are be kicked out of the server at random times, with this error: `io.netty.handler.codec.DecoderException: Unknown serializer type 111`. After this happen, a player cannot ever reconnect, except if I delete its playerdata.
I checked the NBT content of the `playerdata/<UUID>.dat` with a checkdiff between a working player and one kicked out, and there absolutely nothing different except some coordinates/rotations.
I've tried everything (removing maybe 10-20 mods), right now without the mods listed above it is quite okay, but it still happen.

Here are the \*relevant\* logs:
```
[14:01:05] [Render thread/ERROR]: ########## GL ERROR ##########
[14:01:05] [Render thread/ERROR]: @ Post render
[14:01:05] [Render thread/ERROR]: 65540: Invalid scancode -1
[14:01:05] [Netty Epoll Client IO #1/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: Unknown serializer type 111
	at net.minecraft.class_2945.method_12788(class_2945.java:212) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2739.<init>(class_2739.java:28) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:485) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[transformed-mod-minecraft.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
And the full logs are available here: https://mclo.gs/yDDCywe

The mod list is available here (minus ModernFix): https://github.com/Donokami/the-adventurers-journey#projects-bundled-in-this-modpack

[The modpack is open-source](https://github.com/Donokami/the-adventurers-journey), and there is a [docker compose](https://github.com/Donokami/the-adventurers-journey/blob/main/docker-compose.yml) if you ever need to reproduce a server running it. The `0.5.0` version of the modpack is the one where this bug happen the most.

It is running with:
- LWJGL `3.3.1`
- Minecraft `1.19.2`
- Quilt Loader `0.21.0`
- Quilted Fabric API `4.0.0-beta.30+0.76.0`

Thank you in advance for your attention to this bug!

**Comment by Sunconure11** [comment]
Did you ever find the cause? I have a similar issue.
