### ISSUE TITLE
indium Render problem, how to fix that ?

### ISSUE THREAD

**Issue by EinNstiiS** [QuiltMC/quilt-loader#386]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-11-26 13:43:44
Description: Unexpected error

java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197)
	at net.minecraft.class_761.method_3273(class_761.java:15554)
	at net.minecraft.class_761.invokeSetupRender(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:404)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1026)
	at net.minecraft.class_761.handler$chc000$iris$renderTerrainShadows(class_761.java:8553)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$cga000$indium$onRenderBlock(ChunkRenderRebuildTask.java:554)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:325)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView, int)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveBlockQuadTransform.transform(EmissiveBakedModel.java:137)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:102)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:1092)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197)
	at net.minecraft.class_761.method_3273(class_761.java:15554)
	at net.minecraft.class_761.invokeSetupRender(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:404)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1026)
	at net.minecraft.class_761.handler$chc000$iris$renderTerrainShadows(class_761.java:8553)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 1 total; [class_746['GortoI_oer'/110, l='ClientLevel', x=1420.98, y=63.00, z=-535.58]]
	Chunk stats: 1024, 157
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,75,32), Section: (at 0,11,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1400748 game time, 1007337 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, Borderless glass.zip, Mod Menu Helper.zip, VanillaTweaks_r793915.zip, Essential (fabric_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 999494776 bytes (953 MiB) / 1811939328 bytes (1728 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c91
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3640
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=26.20.100.6911
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 19690.13
	Virtual memory used (MB): 17540.83
	Swap memory total (MB): 11661.08
	Swap memory used (MB): 1858.71
	JVM Flags: 9 total; -Xms512M -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.56
		autoreconnect: AutoReconnect 2.1.0-beta
		bclib: BCLib 2.1.7
		bendy-lib: Bendy api 2.1.1
		betterend: Better End 2.1.6
		betterf3: BetterF3 1.4.0
		betterfpsdist: Better FPS distance Mod 1.19.1-2.0
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 2.2.1+1.19.2
			tcdcommons: TCD Commons API 1.1+1.19.2
		blanket-client-tweaks: Blanket Client-tweaks 1.1.2
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		boatiview: Boat Item View Fabric 0.0.4
		brb: Better Recipe Book 1.6.0
		bsvsb: Better Sodium Video Settings Button 3.0.2
		cameraoverhaul: Camera Overhaul 1.3.1-fabric-universal
		camerautils: Camera Utils 1.19.2-1.0.3
		capes: Capes 1.5.2+1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		cateyes: Cat Eyes 6.2.2
		cem: Custom Entity Models 0.7.3-1.19
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		chat_heads: Chat Heads 0.7.1
		cherishedworlds: Cherished Worlds 6.0.4+1.19.4
		chesttracker: Chest Tracker 1.1.18
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		clickthrough: ClickThrough 1.19.1-fabric0.58.5-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.3.103
		continuity: Continuity 2.0.1+1.19
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		deathlog: DeathLog 0.2.11+1.19
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		durabilityplus: DurabilityPlus 1.0.2
		dynamiccrosshair: Dynamic Crosshair 4.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		effective: Effective 1.3
		elementa: Elementa 590
		emotecraft: Emotecraft 2.2.5
			player-animator: Player Animator 0.3.5
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entity_texture_features: Entity Texture Features 4.3.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 13428+deploy-staging+gd302bc70d
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		exordium: Exordium 1.0.1-mc1.19.2
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.4+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fastchest: FastChest 1.3+1.19
		fastload: Fast Load 2.4.4
		fastquit: FastQuit 2.1.0+1.19-1.19.2
		ferritecore: FerriteCore 5.0.3
		fpsdisplay: FPS-Display 1.5.0+1.19
		fpsreducer: FPS Reducer 1.19.2-2.1
		freecam: Freecam 1.1.4
		incendium: Incendium 5.1.6
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		itemscroller: Item Scroller 0.17.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		klmaster: KLMaster 2.0
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.6
		lithium: Lithium 0.10.2
		malilib: MaLiLib 0.13.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		modid: Example Mod 1.0.0
		modmenu: Mod Menu 4.0.6
		nether-coords: Nether Coords 2.0.0
			adventure-platform-fabric: adventure-platform-fabric 5.4.0
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.1
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			clientarguments: clientarguments 1.4.1
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.1
		org_jetbrains_annotations: annotations 13.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		plasmovoice: Plasmo Voice 2.0.5
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		recipe-book-is-pain: Recipe Book Is Pain 0.9.0-1.19.2
			cracker-util: CrackerUtil 0.2.1-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		rrls: Remove Reloading Screen 1.5.0-fabric
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		seedcrackerx: SeedCrackerX 2.13
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 706e4f1b7aa6b42b3627f682a311d06280d80b5c
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		simpleshulkerpreview: Simple Shulker Preview 2.1
		skinlayers: 3d Skin Layers 1.5.1-mc1.19.1
		slotlock: SlotLock 1.1.1-BETA+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.15
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		stendhal: Stendhal 1.3.3-1.19
		tiefix: TieFix 1.11.0
		totemcounter: TotemCounter 1.2.4+mc1.19.2
		ukulib: ukulib 0.6.1+1.19.2
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		universalcraft: UniversalCraft 277
		vigilance: Vigilance 284
		whereisit: Where Is It 1.14.13
		wildfire_gender: Wildfire's Female Gender Mod 1.19-3.0.0
		wmch: Where's My Chat History 1.5.5
		yet-another-config-lib: YetAnotherConfigLib 1.5.0
	Loaded Shaderpack: MakeUp-UltraFast-8.8a.zip
		Profile: Custom (+3 options changed by user)
	NEC status: No NEC detected
	Launched Version: Fabric 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, file/Borderless glass.zip (incompatible), file/Mod Menu Helper.zip, file/VanillaTweaks_r793915.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by FirstMegaGame4** [comment]
I don't think this was at the right place.

**Comment by DefomCode** [comment]
why is the issue closed? how to solve it?!

**Comment by OroArmor** [comment]
This is not the place for support. Please join our discord for support. The forum is currently down.
