### ISSUE TITLE
Chunks not arriving to client

### ISSUE THREAD

**Issue by UnixTMDev** [QuiltMC/quilt-loader#397]
Over LAN, both systems are running Linux, one Mint, one Debian.
Mint (client) has chunks not being rendered, and some also can't be interacted with, as if they weren't sent at all.
Current mod list:
```
AdVitam-1.19.jar
calibrated-1.2.1-hotfix.1+1.19.jar
coyote_time-1.0.0.jar
Croptopia-1.19-FABRIC-2.0.7.jar
DeathKnell-Fabric-1.19-4.1.4.jar
geckolib-quilt-1.19-3.1.14.jar
gravity-api-0.7.18-1.19.jar
haema-1.10.1+1.19.jar
haunted_pants-1.0.0+1.19.jar
modmenu-4.0.4.jar
no-enchant-cap-2.1.2+1.19.jar
Origins-1.19-1.6.2.jar
Pehkui-3.3.3+1.14.4-1.19.1.jar
qfapi-2.0.0-beta.9_qsl-2.0.0-beta.16_fapi-0.58.0_mc-1.19.jar
quilt-kotlin-libraries-0.1.2-MODFEST+kt.1.7.10+flk.1.8.2.jar
relativity-1.0.0-beta.3+1.19.jar
requiem-2.0.0-beta.12.jar
requiem-pandemonium-2.0.0-beta.12.jar
time-in-a-bottle-1.6.2+mc1.19-fabric.jar
voicechat-quilt-1.19-2.4.8.jar
yosbr-0.1.1.jar
```
Feel free to close my issue if this is the wrong place for the issue. Here is a [screenshot](https://github.com/QuiltMC/quilt-loader/assets/107382722/a1325cbf-27af-4aa2-8642-7e3683cc6d50) of gameplay, where the current chunk is not sent at all, and the one being stared at just isn't rendering.
The console just repeats:
```
[18:20:42] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalArgumentException: No value with id 12345
	at net.minecraft.class_2359.method_39974(class_2359.java:19) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2814.method_12289(class_2814.java:74) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2841.method_12326(class_2841.java:174) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2826.method_12258(class_2826.java:169) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:448) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_631.method_16020(class_631.java:102) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_634.method_38539(class_634.java:690) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_634.method_11128(class_634.java:685) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[minecraft-1.19.i0:0/:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [minecraft-1.19.i0:0/:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [minecraft-1.19.i0:0/:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [minecraft-1.19.i0:0/:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [minecraft-1.19.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [minecraft-1.19.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [minecraft-1.19.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [minecraft-1.19.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.23.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.23.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.23.0.jar:?]
```, on the client, where 12345 is always a (seemingly, idk) random number

**Comment by UnixTMDev** [comment]
Fixed, some Fabric-exclusive mods that haven't ported to Quilt sort of 'push' block IDs around, causing all modded blocks to not look like what they are, and chunks with those broken blocks NEVER get sent to any clients. I'll leave this open, seeing as it's still a big issue.
