### ISSUE TITLE
The gui-server encountered an error!

### ISSUE THREAD

**Issue by lmaodick1239** [QuiltMC/quilt-loader#440]
```
Exception in thread "Quilt IPC Handler 1" java.lang.RuntimeException: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,
        at org.quiltmc.loader.impl.gui.BasicWindow.openOnServer(BasicWindow.java:89)
        at org.quiltmc.loader.impl.gui.AbstractWindow.handleUpdate(AbstractWindow.java:157)
        at org.quiltmc.loader.impl.gui.BasicWindow.handleUpdate(BasicWindow.java:200)
        at org.quiltmc.loader.impl.gui.QuiltGuiSyncBase.updateObject(QuiltGuiSyncBase.java:151)
        at org.quiltmc.loader.impl.gui.QuiltForkServerMain.handleMessage0(QuiltForkServerMain.java:161)
        at org.quiltmc.loader.impl.gui.QuiltForkServerMain.handleMessage(QuiltForkServerMain.java:123)
        at org.quiltmc.loader.impl.gui.QuiltForkComms$ReadySender.readMessage(QuiltForkComms.java:379)
        at org.quiltmc.loader.impl.gui.QuiltForkComms$ReadySender.lambda$runReader$0(QuiltForkComms.java:357)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,
        at org.quiltmc.loader.impl.gui.QuiltUI.init(QuiltUI.java:38)
        at org.quiltmc.loader.impl.gui.BasicWindowUI.open(BasicWindowUI.java:96)
        at org.quiltmc.loader.impl.gui.BasicWindow.openOnServer(BasicWindow.java:87)
        ... 10 more
[13:39:44] [Quilt IPC Handler 1/ERROR]: The gui-server encountered an error!
```
probable cause: rendering the unknown files thing caused it to error when requesting a UI instance when running headless
```
[13:46:09] [main/INFO]: 24 unknown / unsupported mod files found:
| Size (Bytes) | Type    | Path                                                       |
|-------------:|---------|------------------------------------------------------------|
|           53 | unknown | <mods>\luckperms\contexts.json                             |
|      744,200 | unknown | <mods>\luckperms\libs\adventure-4.13.0-remapped.jar        |
|      721,359 | unknown | <mods>\luckperms\libs\adventure-4.13.0.jar                 |
|      121,790 | unknown | <mods>\luckperms\libs\asm-9.1.jar                          |
|       72,641 | unknown | <mods>\luckperms\libs\asm-commons-9.1.jar                  |
|    3,661,806 | unknown | <mods>\luckperms\libs\bytebuddy-1.10.22-remapped.jar       |
|    3,510,658 | unknown | <mods>\luckperms\libs\bytebuddy-1.10.22.jar                |
|      931,052 | unknown | <mods>\luckperms\libs\caffeine-2.9.0-remapped.jar          |
|      924,475 | unknown | <mods>\luckperms\libs\caffeine-2.9.0.jar                   |
|      234,258 | unknown | <mods>\luckperms\libs\configurate-core-3.7.2-remapped.jar  |
|      225,808 | unknown | <mods>\luckperms\libs\configurate-core-3.7.2.jar           |
|       12,735 | unknown | <mods>\luckperms\libs\configurate-hocon-3.7.2-remapped.jar |
|       12,166 | unknown | <mods>\luckperms\libs\configurate-hocon-3.7.2.jar          |
|       12,678 | unknown | <mods>\luckperms\libs\event-3.0.0-remapped.jar             |
|       11,782 | unknown | <mods>\luckperms\libs\event-3.0.0.jar                      |
|    2,543,012 | unknown | <mods>\luckperms\libs\h2-driver-2.1.214.jar                |
|      301,603 | unknown | <mods>\luckperms\libs\hocon-config-1.4.1-remapped.jar      |
|      295,197 | unknown | <mods>\luckperms\libs\hocon-config-1.4.1.jar               |
|       19,126 | unknown | <mods>\luckperms\libs\jar-relocator-1.7.jar                |
|      453,064 | unknown | <mods>\luckperms\libs\okhttp-3.14.9-remapped.jar           |
|      430,488 | unknown | <mods>\luckperms\libs\okhttp-3.14.9.jar                    |
|       97,532 | unknown | <mods>\luckperms\libs\okio-1.17.5-remapped.jar             |
|       92,326 | unknown | <mods>\luckperms\libs\okio-1.17.5.jar                      |
|       73,728 | unknown | <mods>\luckperms\luckperms-h2-v2.mv.db                     |
|-------------:|---------|------------------------------------------------------------|
```

**Comment by AlexIIL** [comment]
Can you try updating to loader `0.26.1-beta.1`? I added a few fixes to that version, and I'm not sure which version you're using.

**Comment by lmaodick1239** [comment]
tested it, it still throws the error but wont stop the instance after erroring out. i guess its fine

**Comment by lmaodick1239** [comment]
was using 0.26.0 when error, tested with 0.26.1-beta.1 and no longer breaks instance
