### ISSUE TITLE
quiltmc trying to use internals of fabric loader

### ISSUE THREAD

**Issue by gmelhortecla** [QuiltMC/quilt-loader#75]
i was trying to install fabric api to play with some mods and i got this error

`A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adventure-platform-fabric'!
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
at crystallauncher.MineClient.start(MineClient.java:213)
at crystallauncher.MineClient.main(MineClient.java:36)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adventure-platform-fabric'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
... 9 more
Suppressed: java.lang.ExceptionInInitializerError
at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 11 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
at org.quiltmc.qsl.base.impl.PreLaunchHacks.(PreLaunchHacks.java:49)
... 13 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
at java.base/java.lang.Class.getMethod(Class.java:2227)
at org.quiltmc.qsl.base.impl.PreLaunchHacks.(PreLaunchHacks.java:46)
... 13 more
Caused by: java.lang.ExceptionInInitializerError
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:467)
at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 11 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.(AdventurePrelaunch.java:48)
... 17 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
at java.base/java.lang.Class.getMethod(Class.java:2227)
at net.kyori.adventure.platform.fabric.impl.AdventurePrelaunch.(AdventurePrelaunch.java:45)
... 17 more`

so i went to the fabric api discussion thing and asked for help
i was told that quiltmc was trying to use fabric loader's internals that are removed on the latest version and that i needed to report it

`Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
at java.base/java.lang.Class.getMethod(Class.java:2227)
at org.quiltmc.qsl.base.impl.PreLaunchHacks.(PreLaunchHacks.java:46)`

help pls

**Comment by gmelhortecla** [comment]
![image](https://user-images.githubusercontent.com/104739991/166311589-b859608d-faaa-4101-bb27-1fdfc806b313.png)
i deleted the mods that used fabric api to try to make it work

**Comment by CheaterCodes** [comment]
Just for clarification: You're using quilt-loader, not fabric-loader?
If you are, try replacing fabric-api with quilt-standard-libraries (with bundled quilted-fabric-api): https://modrinth.com/mod/qsl

**Comment by gmelhortecla** [comment]
im using fabric loader, im here because of a comment on a discussion at fabric api's discussion thing

**Comment by CheaterCodes** [comment]
The problem is that quilt-standard-libraries no longer works on fabric. And one of your mods appears to have qsl bundled. You just have to figure out which one it is and remove it.
Alternatively, you could ofc try and run your pack on quilt loader, with the newest qsl from modrinth.

**Comment by gmelhortecla** [comment]
i removed some mods that use fabric + quilt and it worked, it was ok zoomer, thanks for the help!
