### ISSUE TITLE
[CRASH] Game crashed when joining a Singleplayer World

### ISSUE THREAD

**Issue by freeklucas** [QuiltMC/quilt-loader#98]
**What Happens**
The game crashes when I join a Singleplayer world with Minecraft 1.19 with Quilt 0.17,
However, this doesn't happen when I join a Multiplayer server.

**About my system**
OS: GNU/Linux (Debian 11)
Kernel: Linux 5.10.0-16-amd64
Architecture: x86 64-bits
Minecraft Launcher: PolyMC (Flatpak)
Minecraft Version: 1.19
Quilt version: 0.17

**Crash report**
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 16/07/2022, 01:36
Description: Starting integrated server

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:248)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2005)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:265)
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_43326(class_7196.java:179)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:177)
	at net.minecraft.class_7196.method_41894(class_7196.java:57)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:528)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:436)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:372)
	at net.minecraft.class_350.method_25402(class_350.java:359)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243)
	... 49 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [quilted_fabric_message_api_v1.mixins.json:PlayerManagerMixin] from phase [DEFAULT] in config [quilted_fabric_message_api_v1.mixins.json] from mod [quilted_fabric_message_api_v1] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 52 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> quilted_fabric_message_api_v1.mixins.json:PlayerManagerMixin -> Apply Methods -> (Lnet/minecraft/class_5837;Lnet/minecraft/class_3222;Lnet/minecraft/class_2556$class_7602;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$bbn000$onSendChatMessage -> Transform LVT -> var=params -> desc=Lnet/minecraft/class_2556$class_7602;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:533)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:519)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 52 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_2556$class_7602
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1002)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:962)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469)
	... 59 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:248)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2005)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:265)
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_43326(class_7196.java:179)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:177)
	at net.minecraft.class_7196.method_41894(class_7196.java:57)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:528)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:436)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:372)
	at net.minecraft.class_350.method_25402(class_350.java:359)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)

-- Starting integrated server --
Details:
	Level ID: Servivalen
	Level Name: Freek's Let's play
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_43326(class_7196.java:179)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:177)
	at net.minecraft.class_7196.method_41894(class_7196.java:57)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:528)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:436)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:372)
	at net.minecraft.class_350.method_25402(class_350.java:359)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, continuity/default, BlockyCraft DEV9, VanillaTweaks, replaymod_lang
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_43589(class_310.java:822)
	at net.minecraft.class_310.method_1514(class_310.java:723)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.10.0-16-amd64
	Java Version: 17.0.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1429113984 bytes (1362 MiB) / 3498049536 bytes (3336 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258,00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 25627,59
	Virtual memory used (MB): 9482,50
	Swap memory total (MB): 17619,13
	Swap memory used (MB): 0,00
	JVM Flags: 2 total; -Xms512m -Xmx6144m
	Loaded Shaderpack: ComplementaryShaders_v4.3.3
		Profile: Custom (+15 options changed by user)
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		autoclicker-fabric: Auto Clicker 1.19-1.4.0-build.17
		cem: Custom Entity Models 0.7.1
		citresewn: CIT Resewn 1.1.1+1.19
		citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		com_github_llamalad7_mixinextras: MixinExtras 0.0.11
		completeconfig-base: completeconfig-base 2.0.0-beta.3
		completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		continuity: Continuity 2.0.0+1.19
		indium: Indium 1.0.6+mc1.19
		iris: Iris 1.2.5
		itemscroller: Item Scroller 0.16.0
		java: OpenJDK 64-Bit Server VM 17
		lanserverproperties: Lan Server Properties 1.9
		libzoomer: LibZoomer 0.5.0+1.19
		litematica: Litematica 0.11.3
		malilib: MaLiLib 0.12.1
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.22.0
		no-telemetry: No Telemetry 1.4.0
		nochatreports: No Chat Reports 1.19-v1.2.3
		ok_zoomer: Ok Zoomer 5.0.0-beta.9+1.19
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.4
		quilt_advancement: Quilt Advancement API 2.0.0-beta.14+1.19
		quilt_base: Quilt Base API 2.0.0-beta.14+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.14+1.19
		quilt_block_entity: Quilt Block Entity API 2.0.0-beta.14+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.14+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.14+1.19
		quilt_command: Quilt Command API 2.0.0-beta.14+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.14+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.14+1.19
		quilt_item_content_registry: Quilt Item Content Registry API 2.0.0-beta.14+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.14+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.14+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.14+1.19
		quilt_loader: Quilt Loader 0.17.0
		quilt_networking: Quilt Networking 2.0.0-beta.14+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.14+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.14+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.14+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.14+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.14+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.14+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.14+1.19
		quilted_fabric_api: Quilted Fabric API 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_api_base: Quilted Fabric API Base 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 3.0.0-alpha.3+0.57.2-1.19.1
		replaymod: Replay Mod 1.19-2.6.6
		sodium: Sodium 0.4.2+build.16
		spruceui: SpruceUI 4.0.0+1.19
		tweakeroo: Tweakeroo 0.13.3
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.10.0-16-amd64, LLVM 12.0.1) GL version 4.6 (Core Profile) Mesa 21.3.8 (git-813ee839be), AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, continuity/default, file/BlockyCraft DEV9 (incompatible), file/VanillaTweaks (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```

**Comment by triphora** [comment]
You're using the 1.19.1 version of QSL on 1.19.

In the future please do not use GitHub Issues for support, rather prefer our [Discord](https://discord.quiltmc.org/) or [Forum](https://forum.quiltmc.org/)

**Comment by freeklucas** [comment]
@wafflecoffee Oh, sorry, I assumed too quick that it was a bug. My bad.
Anyway, thanks for pointing out what caused the error, I now can join Singleplayer worlds again!
